feat: add nix flake metadata command
flox/runix pull request #2
Opened 2023-02-17 22:33 UTC by phaer

Hello,

this simply adds support for `nix flake metadata` to runix, the only non-trivial thing is that it makes `Git`s `pinned` and `ref` in `ToFlakeRef` optional in order to support locally checked out flakes:
```
nix flake metadata --json | jq '.locked'  
{
  "lastModified": 0,
  "narHash": "sha256-UseRluAkdnsnMNNfX9o4QzdQIhYVv9ssNpyhU5ZnBRI=",
  "type": "git",
  "url": "file:///home/phaer/src/runix"
}
```

The alternative I see would be to use a separate type for things like `locked`, `original` and `resolved` even though they are technically flake references.

2023-03-02 12:08 UTC, ysndr requested changes
Hej!
Great to see you're eager to contribute!

> the only non-trivial thing is that it makes Gits pinned and ref in ToFlakeRef optional in order to support locally checked out flakes:

Yes, there is some irregularities mentioned in #3 already, going to look into that soon.

In terms of the PR, I think the lock abstraction deserves its own module (and `Serialize` derives).
And the flake metadata argument is technically not an installable.

I don't know if you're planning to keep working on this (as its a draft) but i don't mind reviewing any progress on this

2023-03-02 12:08 UTC, ysndr commented on crates/runix/src/command.rs
> +}
These look pretty much like the beginnign of a `flake.lock` representation.
I think we should move those into a separate module and ensure they are tested against an actual lock file

2023-03-02 12:08 UTC, ysndr commented on crates/runix/src/command.rs
> +    pub original: Option<ToFlakeRef>,
Are these ever not present?
if they are not are they `null` or absent?
If `null` should have 
```
#[serde(skip_serializing_if = "Option::is_none")]
```

on it (or bring in [`serde_with`](https://docs.rs/serde_with/latest/serde_with/attr.skip_serializing_none.html))

2023-03-02 12:08 UTC, ysndr commented on crates/runix/src/command.rs
> +    pub inputs: HashMap<String, String>,
```
    pub inputs: HashMap<String, String>,
                                L can be a list (path) if a `follows` entry
```

2023-03-02 12:08 UTC, ysndr commented on crates/runix/src/command.rs
> +    pub url: String,
It's both urls (which should be parseable with Installable)
I't a bit of redundant information in here and I'd be inclined to skip reading those, and only serialize them from the other parts in the struct

2023-03-02 12:08 UTC, ysndr commented on crates/runix/src/command.rs
> +    const SUBCOMMAND: &'static [&'static str] = &["flake", "metadata"];
On this matter I think we have found a new kind of command, one that takes a flake-ref (not an installable)
Not sure if its common enough to warrant another group, but it should be modeled as an argument on `FlakeMetadata`'s `Own` type.

Thousgh right now De-/Serialization of some flakeRefs is not fully implemented yet, so we got to go with `String` or `Url` until then

See `Develop` below as an example

2023-03-08 15:42 UTC, phaer commented
@ysndr  Thanks for your review! I should have updated this, but I currently don't plan to continue this work as I've stopped using Runix for the time being.

2023-03-08 15:42 UTC, closed without merging

2023-03-09 21:28 UTC, ysndr commented
Thanks for letting us know.
We'll likely work on a similar feature too, soon.
I'll let you know.