feat: add LegacyArgs, --store, and --eval-store
flox/runix pull request #37
Opened 2023-07-26 23:09 UTC by mkenigs

2023-07-27 09:20 UTC, ysndr requested changes

2023-07-27 09:20 UTC, ysndr commented on crates/runix/src/arguments/legacy.rs
I meant for these to be part of the `NixCommonArgs` (in `common.rs`) since they are available to any nix (sub) command (see `nix --help`).

2023-07-31 15:30 UTC, mkenigs commented on crates/runix/src/arguments/legacy.rs
Moved!

2023-08-01 09:58 UTC, ysndr approved these changes

2023-08-01 09:58 UTC, merged